### ISSUE TITLE
Errors in the demo example

### ISSUE THREAD

**Issue by aswinmprabhu** [sahilm/fuzzy#10]
The initialization of `g` is 
`g, err = gocui.NewGui(gocui.OutputNormal)`
instead of 
`g, err := gocui.NewGui(gocui.OutputNormal)`

The usage of `g` in the finder function gives an error saying `g is undefined` as `g` is declared in the main function.

**Comment by sahilm** [comment]
`g` and `err` are defined globally and I can't see why the example won't work.
https://github.com/sahilm/fuzzy/blob/485b11793d7eabbfd950d919306b62242004e5e5/_example/main.go#L17-L21

Could you please share the exact error message you get when you run the following:
```bash
cd _example/
go get -u github.com/jroimartin/gocui
go run main.go
```

**Comment by aswinmprabhu** [comment]
Sorry. I missed the global declaration. I didn't run it but just referred to it for my use case. My bad. Thanks for the great library :)
