### ISSUE TITLE
Request for New Tag (v0.1.1)

### ISSUE THREAD

**Issue by arthurbdiniz** [sahilm/fuzzy#23]
Some Debian packages have been utilizing the functionality provided by the fuzzy library and recently came across a commit that I believe would greatly benefit the community.

Specifically, I am referring to the commit with the hash https://github.com/sahilm/fuzzy/commit/c48e322e2a8f19bbd962faf82eee4cf11dbf81ba that adds the feature **feat: fuzzy find without sorting**.

Would it be possible for you to create a new tag like **v0.1.1** on the repository?

This would facilitate easier referencing and usage by other developers who rely on your library within the Debian ecosystem.

Your assistance would contribute integration of the fuzzy library within Debian packaging.

Thank you for your time and consideration.

**Comment by sahilm** [comment]
https://github.com/sahilm/fuzzy/releases/tag/v0.1.1

Hope this helps.

**Comment by arthurbdiniz** [comment]
Thanks
