### ISSUE TITLE
benchmarks comparison with similar fuzzy search engines in Go

### ISSUE THREAD

**Issue by bacongobbler** [sahilm/fuzzy#3]
It might be fun/educational to compare/contrast the benchmark results posted here against other existing fuzzy search engines such as https://github.com/renstrom/fuzzysearch and see how they all stack up. :)

**Comment by sahilm** [comment]
That's a great idea. @ericpauley has just dropped a massive optimisation in #4. He rewrote my crap code into good code :)

Maybe once I digest and merge #4 we can arrange a showdown.

**Comment by EduardoRT** [comment]
Another one for the comparison list.

https://github.com/junegunn/fzf

**Comment by sahilm** [comment]
I looked at the mentioned projects. The other fuzzy matching lib uses a completely different algorithm and fzf isn't really a library.

fuzzy is now very fast and results are near instantaneous. I think comparisons won't be apples to apples. Let's revisit this when they're more such libs.
