### ISSUE TITLE
'\' as separator?

### ISSUE THREAD

**Issue by raghur** [sahilm/fuzzy#7]
Looks like this uses only '/' as separator - but for windows, using just '\' or both '\' and '/' as separators will lead to better results

**Comment by sahilm** [comment]
Thanks! I'll add `\` as a separator and cut a new release. Are you using/plan to use this library for anything interesting? It'll be nice to see what people want to use fuzzy for.

**Comment by sahilm** [comment]
Tag `v0.0.5` released.

**Comment by raghur** [comment]
I'm using this as a vim plugin - with denite.vim - https://github.com/raghur/fuzzy-denite

**Comment by sahilm** [comment]
Awesome. Let me know if you run into anything else.
